[local]
localhost

[mongodb]
mongodb-dev.rkak87.online

[catalogue]
catalogue-dev.rkak87.online

[redisdb]
redisdb-dev.rkak87.online

[user]
user-dev.rkak87.online

[cart]
cart-dev.rkak87.online

[mysql]
mysql-dev.rkak87.online

[shipping]
shipping-dev.rkak87.online

[rabbitmq]
rabbitmq-dev.rkak87.online

[payment]
payment-dev.rkak87.online

[frontend]
frontend-dev.rkak87.online

[dispatch]
dispatch-dev.rkak87.online