- name: "Configure the Roboshop Application in Dev Environment"
  hosts: "{{ component }}"
  become: true
  tasks:
    - name: "Display Message"
      ansible.builtin.debug:
        msg: "Configuring the {{ component }} component in Dev Environment"
  roles:
  - "{{ component }}"